name: select
description: Code generation for selectors of class fields that helps reduce repetitive code.
version: 0.1.0
maintainer: Yakov Karpov (@purplenoodlesoop)

homepage: https://github.com/purplenoodlesoop/select/tree/master/packages/select


environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  analyzer: ^3.0.0

  build: ^2.3.0
  source_gen: ^1.2.2

  code_builder: ^4.1.0

  meta: ^1.7.0
  select_annotation: ^0.1.0


dev_dependencies:
  purple_lints: ^0.2.0
